
spring:
  datasource:
    url: jdbc:mysql://localhost:32770/health
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
  resources:
    add-mappings: true