server:
    context-path: /health
spring:
  datasource:
    url: jdbc:mysql://localhost:32770/health
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
  resources:
    add-mappings: true
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
